Added a secondary Cross (Blue) default at light level 1
shedaniel/LightOverlay-Fabric pull request #43
Opened 2020-06-08 10:03 UTC by ModProg

I found this useful mainly for strip mining,  the blue cross is the correct position for a new torch in that case. 

ModMenu:
![grafik](https://user-images.githubusercontent.com/11978847/84017892-9e4cde80-a97f-11ea-8947-2c2d14d88b94.png)

This commit also includes a fix for Pre-2, if this collides with anything I can remove that.
It's only one change (`getMaximum` to `getMax`)

I developed the feature for 1.15 as well, but I didn't want to create two identical pull requests.

This is mainly something I did for private use, but I cleaned up my code, so in case there is interest in such a feature in LightOverlay I made this pull request

2020-06-08 10:24 UTC, shedaniel requested changes
Would want to have a boolean toggle to this optimal placement cross (what you call as secondary cross)

Otherwise, change the names and lgtm

2020-06-08 10:24 UTC, shedaniel commented on src/main/resources/assets/lightoverlay/lang/en_us.json
> +  "config.lightoverlay.crossLevel2": "Light Level Secondary:",
```suggestion
  "config.lightoverlay.optimalPlacementLevel": "Optimal Placement Level:",
```

2020-06-08 10:24 UTC, shedaniel commented on src/main/resources/assets/lightoverlay/lang/en_us.json
> +  "config.lightoverlay.secondaryColor": "Secondary Color:",
```suggestion
  "config.lightoverlay.optimalPlacementColor": "Optimal Placement Color:",
```

2020-06-08 10:24 UTC, shedaniel commented on src/main/java/me/shedaniel/lightoverlay/fabric/LOModMenuEntry.java
> +        general.addEntry(eb.startIntSlider(new TranslatableText("config.lightoverlay.crossLevel2"), LightOverlay.crossLevel2, 0, 15).setDefaultValue(1).setTextGetter(integer -> new LiteralText("Secon
```suggestion
        general.addEntry(eb.startIntSlider(new TranslatableText("config.lightoverlay.optimalPlacementLevel"), LightOverlay.optimalPlacementLevel, 0, 15).setDefaultValue(1).setTextGetter(integer -> new LiteralText("Level: " + integer)).setSaveConsumer(integer -> LightOverlay.optimalPlacementLevel = integer).build());
```

2020-06-08 10:24 UTC, shedaniel commented on src/main/java/me/shedaniel/lightoverlay/fabric/LOModMenuEntry.java
>          general.addEntry(eb.startIntSlider(new TranslatableText("config.lightoverlay.crossLevel"), LightOverlay.crossLevel, 0, 15).setDefaultValue(7).setTextGetter(integer -> new LiteralText("Cross L
```suggestion
        general.addEntry(eb.startIntSlider(new TranslatableText("config.lightoverlay.crossLevel"), LightOverlay.crossLevel, 0, 15).setDefaultValue(7).setTextGetter(integer -> new LiteralText("Level: " + integer)).setSaveConsumer(integer -> LightOverlay.crossLevel = integer).build());
```

2020-06-08 10:24 UTC, shedaniel commented on src/main/java/me/shedaniel/lightoverlay/fabric/LOModMenuEntry.java
> +        general.addEntry(eb.startColorField(new TranslatableText("config.lightoverlay.secondaryColor"), LightOverlay.secondaryColor).setDefaultValue(0x0000FF).setSaveConsumer(color -> LightOverlay.se
```suggestion
        general.addEntry(eb.startColorField(new TranslatableText("config.lightoverlay.optimalPlacementColor"), LightOverlay.optimalPlacementColor).setDefaultValue(0x0000FF).setSaveConsumer(color -> LightOverlay.optimalPlacementColor = color).build());
```

2020-06-08 10:24 UTC, shedaniel commented on src/main/java/me/shedaniel/lightoverlay/fabric/LightOverlay.java
> +    static int yellowColor = 0xFFFF00, redColor = 0xFF0000, secondaryColor = 0x0000FF;
```suggestion
    static int yellowColor = 0xFFFF00, redColor = 0xFF0000, optimalPlacementColor = 0x0000FF;
```

2020-06-08 12:18 UTC, ModProg commented
It can now be disabled by setting it to "-1".
I didn't name it Optimal placement Level, because of that being 2 for diagonals.
But as the light level can be changed this is something the user can change to his liking.

Should there be indication that the "Placement Level" is a "Light Level" as well?
![grafik](https://user-images.githubusercontent.com/11978847/84029270-68652580-a992-11ea-9ee2-6bf2784beb49.png)
![grafik](https://user-images.githubusercontent.com/11978847/84029315-74e97e00-a992-11ea-98d8-06dd7a86130d.png)

2020-06-08 12:21 UTC, shedaniel commented
maybe do `Hint Light Level`, also this should be disabled by default.

Also what is the optimal location?

2020-06-08 12:35 UTC, ModProg commented
It is light level 2 diagonally and 1 in a straight line.

![grafik](https://user-images.githubusercontent.com/11978847/84031070-58027a00-a995-11ea-8682-9d6a8ca37b3d.png)

2020-06-08 12:37 UTC, ModProg commented
Should I add an Info like that? 
To the slider maybe:
Level: 1 (opt. straight)

2020-06-08 12:38 UTC, shedaniel commented
maybe we could overhaul this whole feature to make it not user customizable for the level, but can display the optimal place to place torches and stuff?

2020-06-08 12:50 UTC, ModProg commented
That would probably be quite a complex.
For a plane simply placing diagonally every 7 places in a grid fits.

But for complex shapes there are more than one answer, and the calculation would probably make the whole thing lag.
An example with 1 torch behind a wall, the optimal solution would need to place one of the top torches 1 block to the center, so it is not even symmetrical even tho the setup it self is.
![grafik](https://user-images.githubusercontent.com/11978847/84031919-ceec4280-a996-11ea-839f-25db27af3e0f.png)
Here is a showing optimal torch placement, but it's also just a check for light level = 2

2020-06-08 12:54 UTC, ModProg commented
The only thing I could think of that could work, would be to check if a placement of the configured level is close enough to the current location, but even that would require to check for "line of sight" to all viable blocks close enough.

2020-06-08 13:08 UTC, shedaniel commented
This is good enough then, I will merge this within a few hours

2020-06-08 13:08 UTC, shedaniel approved these changes

2020-06-08 13:14 UTC, ModProg commented
Well an algorithm probably working would be:
```java
if(light_level > 7) return None;
for(int placement_level = 0; placement_level < light_level; placement_level++){
    foreach(block in getBlocksAirAboveBlockLessThen7BlocksAway()){
        block = torch;
        if(calculate_current_light > 7) return Red;
    }
}
return Blue
```

2020-06-21 13:58 UTC, merged

2020-06-22 03:49 UTC, ModProg commented
Should I make the pull request for 1.15 as well?

2020-06-22 05:07 UTC, shedaniel commented
I have already done that, just didn't push